
ASTERIKS= "*"
SPACE= "  "
print(SPACE + ASTERIKS + SPACE*3 + ASTERIKS + SPACE*4 + ASTERIKS*2 + SPACE*5 + ASTERIKS*4 + SPACE*4 + ASTERIKS*4 + SPACE*4 + ASTERIKS + SPACE*3+ ASTERIKS)
print(SPACE + ASTERIKS + SPACE*3 + ASTERIKS + SPACE*3 + ASTERIKS + SPACE*2 + ASTERIKS + SPACE*4 + ASTERIKS + SPACE*2 + ASTERIKS +  SPACE*3 + ASTERIKS + SPACE*2 + ASTERIKS + SPACE*3 + ASTERIKS + SPACE*3 + ASTERIKS )
print(SPACE + ASTERIKS*8 + SPACE*2 +ASTERIKS + SPACE*4 +ASTERIKS + SPACE*3 + ASTERIKS*4 + SPACE*4 + ASTERIKS*4 + SPACE*5 +ASTERIKS + SPACE + ASTERIKS )
print(SPACE + ASTERIKS + SPACE*3 +ASTERIKS + SPACE*2 +ASTERIKS*10 + SPACE*3 + ASTERIKS + SPACE*2+ ASTERIKS + SPACE*3 + ASTERIKS + SPACE*2 + ASTERIKS + SPACE*5 +ASTERIKS )
print(SPACE + ASTERIKS + SPACE*3 +ASTERIKS +SPACE*2 + ASTERIKS + SPACE*4 + ASTERIKS + SPACE*3 + ASTERIKS + SPACE*3 + ASTERIKS + SPACE*2 + ASTERIKS + SPACE*3 + ASTERIKS + SPACE*4 + ASTERIKS)



