

SPACE= "  "
CARET= "^"
PLUS= "+"
MINUS= " - "
QUOTATION="'"
LEFT_PARENTHESIS="("
RIGHT_PARENTHESIS=")"
UNDERSCORE= "__"
VERTICAL_BAR= "|"
DOT="."

print(SPACE*9+ PLUS )
print(SPACE*8+ PLUS +SPACE*2 + PLUS)
print(SPACE*7 + PLUS + SPACE*4 + PLUS )
print(SPACE*6 + PLUS +MINUS*4 +PLUS )
print(SPACE*6 +VERTICAL_BAR + SPACE*2 + DOT + MINUS + DOT + SPACE*2 + VERTICAL_BAR)
print(SPACE*6 +VERTICAL_BAR + SPACE*2 + LEFT_PARENTHESIS + SPACE + RIGHT_PARENTHESIS + SPACE*2 + VERTICAL_BAR)
print(SPACE*5  +SPACE  + SPACE + PLUS )
