
SPACE= "  "
CARET= "^"
PLUS= "+"
MINUS= " - "
QUOTATION="'"
DOUBLE_QUOTATION= ' " '
LEFT_PARENTHESIS="("
RIGHT_PARENTHESIS=")"
O= "0"
UNDERSCORE= "__"
VERTICAL_BAR= "|"
SLASH= " / "

print(SPACE*10 + SLASH*5)
print(SPACE*10 + DOUBLE_QUOTATION*5)
print(SPACE*10+ PLUS + SPACE*6 + PLUS)
print(SPACE*9+LEFT_PARENTHESIS + VERTICAL_BAR + SPACE*2 + O + SPACE*2 + O + SPACE*2+ VERTICAL_BAR + RIGHT_PARENTHESIS )
print(SPACE*10 + VERTICAL_BAR + SPACE*3 + CARET + SPACE + SPACE*2 + VERTICAL_BAR)
print(SPACE*10 + VERTICAL_BAR + SPACE+SPACE + QUOTATION + UNDERSCORE + QUOTATION + SPACE +SPACE*2 + VERTICAL_BAR)
print(SPACE*10+ PLUS + UNDERSCORE*6 + PLUS)